source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

use_frameworks!

target 'TFNetwork_Example' do
  pod 'TFNetwork', :path => '../'

  target 'TFNetwork_Tests' do
    inherit! :search_paths

    
  end
end
